site_name: 'Automated testing with Github Actions'
repo_url: https://github.com/matpiq/PF-TDD
edit_uri: edit/main/docs/

nav:
  - Introduction to Continuous Integration with Github Actions: intro.md
  - Continuous (py)Testing: pytest.md
  - Exercise in pairs: exercise.md
  - Typechecking, linting and formatting: linting-formatting.md

theme:
  features:
  #   - navigation.tabs
    - navigation.expand
    - navigation.instant
    #- navigation.tabs.sticky
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details


extra_javascript:
  # Mathjax support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
