site_name: 'Test Driven Development in Practice'
repo_url: https://github.com/matpiq/PF-TDD
edit_uri: edit/main/docs/

nav:
  - Course Overview: index.md
  - Testing with Python: testing_python.md
  - Automated testing using Github actions: testing_github.md
  - Putting it all together: testing_workflow.md
  - Exercises: exercises.md
  - Advanced Topics: testing_advanced.md

theme:
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    #- navigation.tabs.sticky
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


extra_javascript:
  # Mathjax support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
